<?php
$controllerName     = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$actionName         = Zend_Controller_Front::getInstance()->getRequest()->getActionName();

echo $this->doctype();
?>

<!--[if lt IE 7]><html class="no-js ie6 oldie" lang="en"><![endif]-->
<!--[if IE 7]><html class="no-js ie7 oldie" lang="en"><![endif]-->
<!--[if IE 8]><html class="no-js ie8 oldie" lang="en"><![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>

<?php echo $this->headMeta() ?>


<?php echo $this->headTitle() ?>


<?php echo $this->headLink() ?>



<?php echo $this->headStyle() ?>


<?php echo $this->headScript() ?>

</head>
<body id="<?php echo $controllerName;?>" class="<?php echo $actionName;?>">

<div class="wrapper">
<!--#header-->
<div id="header">
<h1><a href="#"><span>WRS</span> Production <span>Tools</span></a></h1>
</div>

<!--#content-->
<div id="content">
<?php echo $this->layout()->content ?>
</div>


<div class="clear"></div>

</div>

<?php echo $this->jQuery() ?>
<?php echo $this->inlineScript() ?>
</body>
</html>
