--  Generate SQL 
--  Version:                   	V5R4M0 060210 
--  Generated on:              	03/08/12 11:53:17 
--  Relational Database:       	S10F6F71 
--  Standards Option:          	DB2 UDB iSeries 
DROP TABLE APLUS08FIN.PT_WOR ; 
  
CREATE TABLE APLUS08FIN.PT_WOR ( 
	ID INTEGER GENERATED ALWAYS AS IDENTITY ( 
	START WITH 1 INCREMENT BY 1 
	NO MINVALUE NO MAXVALUE 
	NO CYCLE NO ORDER 
	CACHE 20 ) 
	, 
	AUTHOR VARCHAR(100) ALLOCATE(2) CCSID 37 DEFAULT 'NA' , 
	BO_VALUE DOUBLE PRECISION DEFAULT NULL , 
	CREATED INTEGER NOT NULL , 
	HEADINGS CLOB(300) CCSID 37 DEFAULT NULL , 
	RECORD_COUNT FOR COLUMN RCOUNT     INTEGER DEFAULT NULL , 
	REPORT VARCHAR(255) ALLOCATE(13) CCSID 37 DEFAULT 'NOT Specified' , 
	UPDATED INTEGER DEFAULT NULL , 
	WORK_CENTER_GROUPS FOR COLUMN WGCS       CLOB(2048) CCSID 37 DEFAULT NULL , 
	WORK_CENTERS FOR COLUMN WCS        CLOB(300) CCSID 37 DEFAULT NULL , 
	"ROWS" CLOB(2097152) CCSID 1208 DEFAULT NULL )   
	; 
  
LABEL ON TABLE APLUS08FIN.PT_WOR 
	IS 'Production Tools Application Work Order Report Tab' ; 
  
LABEL ON COLUMN APLUS08FIN.PT_WOR 
( ID IS 'ID COLUMN            ' , 
	AUTHOR IS 'AUTHOR              AUTHOR              AUTHOR' , 
	BO_VALUE IS 'BACK ORDER VALUE    BACK ORDER VALUE    BACK ORDER VALUE' , 
	CREATED IS 'TIMESTAMP           TIMESTAMP           TIMESTAMP' , 
	HEADINGS IS 'TABLE HEADINGS      TABLE HEADINGS      TABLE HEADINGS' , 
	RECORD_COUNT IS 'NUMBER OF RECORDS   NUMBER OF RECORDS   NUMBER OF RECORDS' , 
	REPORT IS 'REPORT NAME         REPORT NAME         REPORT NAME' , 
	UPDATED IS 'UPDATE TIMESTAMP    UPDATE TIMESTAMP    UPDATE TIMESTAMP' , 
	WORK_CENTER_GROUPS IS 'WORK CENTER GROUPS  WORK CENTER GROUPS  WORK CENTER GROUPS' , 
	WORK_CENTERS IS 'WORK_CENTERS        WORK_CENTERS        WORK_CENTERS' , 
	"ROWS" IS 'ROWS                ROWS                ROWS' ) ; 
  
LABEL ON COLUMN APLUS08FIN.PT_WOR 
( AUTHOR TEXT IS 'NAME OF PERSON WHO CREATED THE CRECORD' , 
	BO_VALUE TEXT IS 'BACK ORDER VALUE' , 
	CREATED TEXT IS 'TIMESTAMP OF WHEN THE RECORD WAS CREATED' , 
	HEADINGS TEXT IS 'TABLE HEADINGS (JSON ENCODED)' , 
	RECORD_COUNT TEXT IS 'NUMBER OF RECORDS' , 
	REPORT TEXT IS 'REPORT NAME' , 
	UPDATED TEXT IS 'TIMESTAMP OF WHEN RECORD WAS UPDATED' , 
	WORK_CENTER_GROUPS TEXT IS 'WORK CENTER GROUPS (PHP Serialized)' , 
	WORK_CENTERS TEXT IS 'WORK_CENTERS (PHP Serialized)' , 
	"ROWS" TEXT IS 'TABLE ROW DATA (PHP Serialized)' ) ;
