<div class="breadcrumbs">
<?php echo($this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render());?>
</div>

<div class="sectionHeader enlarge">
<h1>GET work-center/</h1>
</div>

<!-- #apiDocLeftColumn -->
<div id="apiDocLeftColumn">

<div class="generalContent">
<p class="updatedOn">Updated on <?php echo $this->fileUpdated;?></p>
<p>Returns list of all the work centers in the AS/400 WOWCM database table.</p>
<h5>Resource URL</h5>
<p>http://api.productiontoolsv2.com/rest/work-center</p>
</div>

<table>
<thead>
<tr>
<th colspan="2">No Parameters</th>
</tr>
</thead>
</table>
</div>

<!-- #apiDocRightColumn -->
<div id="apiDocRightColumn">

<div class="resourceInformation">

<div class="resourceInformationTitle">Resource Information</div>

<table>
<tbody>
<tr>
<td>Requires Authentication?</td>
<td>Yes</td>
</tr>
<tr>
<td>Response Formats</td>
<td>json</td>
</tr>
<tr>
<td>HTTP Methods</td>
<td>GET</td>
</tr>
</tbody>
</table>
</div>

</div>


<div class="clear"></div>

