<div class="breadcrumbs">
<?php echo($this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render());?>
</div>

<div class="sectionHeader enlarge">
<h1>GET work-order-status/</h1>
</div>

<!-- #apiDocLeftColumn -->
<div id="apiDocLeftColumn">

<div class="generalContent">
<p class="updatedOn">Updated on <?php echo $this->fileUpdated;?></p>
<p>Returns list of work order status(es) from the AS/400.</p>
<h5>Resource URL</h5>
<p>http://api.productiontoolsv2.com/rest/work-order-status</p>
</div>

<table>
<thead>
<tr>
<th colspan="2">Parameters <span>(Ordered by name)</span></th>
</tr>
</thead>
<tbody>

<tr>
<td>
<div class="param">id</div>
<div class="paramUse">optional</div>
<div class="paramUse chainSupported">supports chained values</div>
</td>
<td>
<div>Restricts results to a particular work order status id(s).</div>
<div class="exampleValues"><span>Example Value:</span> 21</div>
<div>When chaining, make sure to separate each field with a comma. To validate as a valid HTTP path there cannot be any whitespaces on either side of each comma. </div>
<div class="exampleValues"><span>Chaining Example Value:</span> 21,32</div>
</td>
</tr>

</tbody>
</table>
</div>

<!-- #apiDocRightColumn -->
<div id="apiDocRightColumn">

<div class="resourceInformation">

<div class="resourceInformationTitle">Resource Information</div>

<table>
<tbody>
<tr>
<td>Requires Authentication?</td>
<td>Yes</td>
</tr>
<tr>
<td>Response Formats</td>
<td>json</td>
</tr>
<tr>
<td>HTTP Methods</td>
<td>GET</td>
</tr>
</tbody>
</table>
</div>

</div>


<div class="clear"></div>

