<div class="breadcrumbs">
<?php echo($this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render());?>
</div>

<div class="sectionHeader enlarge">
<h1>GET report/</h1>
</div>

<!-- #apiDocLeftColumn -->
<div id="apiDocLeftColumn">

<div class="generalContent">
<p class="updatedOn">Updated on <?php echo $this->fileUpdated;?></p>
<p>Returns PHP translated AS/400 report based upon the provided report name.</p>
<h5>Resource URL</h5>
<p>http://api.productiontoolsv2.com/rest/report</p>
</div>

<table>
<thead>
<tr>
<th colspan="2">Parameters <span>(Ordered by requirement, then by name)</span></th>
</tr>
</thead>
<tbody>

<tr class="mandatory">
<td>
<div class="param">run</div>
<div class="paramUse">mandatory</div>
</td>
<td>
<div>Specifies the name of the report that is to be executed.</div>
<div class="exampleValues"><span>Example Value:</span> WO1010RG</div>
<div>The following are the supported reports:</div>
<div>
<ul>
<li>WO1010RG</li>
<li>WO1002RG</li>
</ul>
</div>
</td>
</tr>


<tr>
<td>
<div class="param">limit</div>
<div class="paramUse">optional</div>
</td>
<td>
<div>Limits the number of records returned</div>
<div class="exampleValues"><span>Example Value:</span> 22</div>
</td>
</tr>


<tr>
<td>
<div class="param">order-by</div>
<div class="paramUse">optional</div>
<div class="paramUse chainSupported">supports chained values</div>
<div class="paramUse bold">Sub-values are mandatory when using chained values.</div>
</td>
<td>
<div>Orders the final results by specified field(s) and order types (ascending or descending). Each order-by field requires one sub-value which is separated by a colon (:).</div>
<div class="exampleValues"><span>Example Value:</span> back-order-quantity<b style="color:blue">:</b>desc</div>
<div>When chaining, make sure to separate each field with a comma. To validate as a valid HTTP path there cannot be any whitespaces on either side of each comma. </div>
<div class="exampleValues"><span>Chaining Example Value:</span> order-number:asc,back-order-quantity:desc</div>
<div>The following are the supported order-by fields:</div>
<div>
<ul>
<li>back-order-quantity</li>
<li>order-number</li>
<li>order-quantity</li>
<li>order-status</li>
</ul>
</div>
<div>The following are the supported sub-values:</div>
<div>
<ul>
<li>asc (for ascending)</li>
<li>desc (for descending)</li>
</ul>
</div>
</td>
</tr>


<tr>
<td>
<div class="param">order-status</div>
<div class="paramUse">optional</div>
<div class="paramUse chainSupported">supports chained values</div>
</td>
<td>
<div>Restricts results to a particular order status.</div>
<div class="exampleValues"><span>Example Value:</span> 21</div>
<div>When chaining order statuses, make sure to separate each order status with a comma. To validate as a valid HTTP path there cannot be any whitespaces on either side of each comma.</div>
<div class="exampleValues"><span>Chaining Example Value:</span> 21,3</div>
<div>The following are the supported order-status values:</div>
<div>
<table class="orderStatusList">
<thead>
<tr>
<th>ID #</th>
<th>Definition</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td>
<td>Release Ready</td>
</tr>
<tr>
<td>2</td>
<td>Released</td>
</tr>
<tr>
<td>20</td>
<td>Released - Material Short</td>
</tr>
<tr>
<td>21</td>
<td>Pck Ready</td>
</tr>
<tr>
<td>3</td>
<td>Confirmed</td>
</tr>
<tr>
<td>31</td>
<td>Material Short</td>
</tr>
<tr>
<td>32</td>
<td>Pck Ready</td>
</tr>
<tr>
<td>9</td>
<td>Material Short</td>
</tr>
</tbody>
</table>
</div>
</td>
</tr>


<tr>
<td>
<div class="param">order-number</div>
<div class="paramUse">optional</div>
</td>
<td>
<div>Restricts results to a particular order number.</div>
<div class="exampleValues"><span>Example Value:</span> Y0751</div>
</td>
</tr>


<tr>
<td>
<div class="param">order-status</div>
<div class="paramUse">optional</div>
<div class="paramUse chainSupported">supports chained values</div>
</td>
<td>
<div>Restricts results to a particular order status.</div>
<div class="exampleValues"><span>Example Value:</span> 21</div>
<div>When chaining order statuses, make sure to separate each order status with a comma. To validate as a valid HTTP path there cannot be any whitespaces on either side of each comma.</div>
<div class="exampleValues"><span>Chaining Example Value:</span> 21,3</div>
</td>
</tr>


<tr>
<td>
<div class="param">work-center</div>
<div class="paramUse">optional</div>
<div class="paramUse chainSupported">supports chained values</div>
</td>
<td>
<div>Restricts results to a particular work center(s).</div>
<div class="exampleValues"><span>Example Value:</span> 43</div>
<div>When chaining work centers, make sure to separate each order status with a comma. To validate as a valid HTTP path there cannot be any whitespaces on either side of each comma.</div>
<div class="exampleValues"><span>Chaining Example Value:</span> ASBLY,43</div>
</td>
</tr>

</tbody>
</table>
</div>

<!-- #apiDocRightColumn -->
<div id="apiDocRightColumn">

<div class="resourceInformation">

<div class="resourceInformationTitle">Resource Information</div>

<table>
<tbody>
<tr>
<td>Requires Authentication?</td>
<td>Yes</td>
</tr>
<tr>
<td>Response Formats</td>
<td>json</td>
</tr>
<tr>
<td>HTTP Methods</td>
<td>GET</td>
</tr>
</tbody>
</table>
</div>

</div>


<div class="clear"></div>

