<div class="breadcrumbs">
<?php echo($this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render());?>
</div>

<div class="sectionHeader enlarge">
<h1>PUT work-center-group/</h1>
</div>

<!-- #apiDocLeftColumn -->
<div id="apiDocLeftColumn">

<div class="generalContent">
<p class="updatedOn">Updated on <?php echo $this->fileUpdated;?></p>
<p>Submit new work center group to the database.</p>
<h5>Resource URL</h5>
<p>http://api.productiontoolsv2.com/rest/work-center-group</p>
</div>

<table>
<thead>
<tr>
<th colspan="2">Parameters <span>(Ordered by name)</span></th>
</tr>
</thead>
<tbody>

<tr class="mandatory">
<td>
<div class="param">description</div>
<div class="paramUse">mandatory</div>
</td>
<td>
<div>Sets the description for the group. This must be first utf8 encoded, then url encoded in order to pass HTTP path validation.</div>
<div class="exampleValues"><span>Example Value:</span> hello,%20cruel%20world.</div>
</td>
</tr>


<tr class="mandatory">
<td>
<div class="param">group-id</div>
<div class="paramUse">mandatory</div>
</td>
<td>
<div>Sets the group id.</div>
<div class="exampleValues"><span>Example Value:</span> B</div>
</td>
</tr>


<tr class="mandatory">
<td>
<div class="param">staffing</div>
<div class="paramUse">mandatory</div>
</td>
<td>
<div>Sets the staffing level for the group.</div>
<div class="exampleValues"><span>Example Value:</span> 4</div>
</td>
</tr>


<tr class="mandatory">
<td>
<div class="param">work-center</div>
<div class="paramUse">manadtory</div>
<div class="paramUse chainSupported">supports chained values</div>
</td>
<td>
<div>Sets the work center(s) that are a part of the group.</div>
<div class="exampleValues"><span>Example Value:</span> 43</div>
<div>When chaining work centers, make sure to separate each order status with a comma. To validate as a valid HTTP path there cannot be any whitespaces on either side of each comma.</div>
<div class="exampleValues"><span>Chaining Example Value:</span> ASBLY,43</div>
</td>
</tr>

</tbody>
</table>
</div>

<!-- #apiDocRightColumn -->
<div id="apiDocRightColumn">

<div class="resourceInformation">

<div class="resourceInformationTitle">Resource Information</div>

<table>
<tbody>
<tr>
<td>Requires Authentication?</td>
<td>Yes</td>
</tr>
<tr>
<td>Response Formats</td>
<td>json</td>
</tr>
<tr>
<td>HTTP Methods</td>
<td>
<a href="<?php echo $this->url(array('controller' => 'api-documentation', 'action' => 'get-work-center-group'));?>">GET</a>
<br/>
PUT
<br/>
<a href="<?php echo $this->url(array('controller' => 'api-documentation', 'action' => 'delete-work-center-group'));?>">DELETE</a>
</td>
</tr>
</tbody>
</table>
</div>

</div>


<div class="clear"></div>

